# Generated by Django 4.1.4 on 2023-03-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
